# Generated by Django 2.1.8 on 2019-10-09 14:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FNSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('userimg', models.ImageField(upload_to='userimg')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='아이디')),
                ('email', models.EmailField(max_length=30, verbose_name='사용자이메일')),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='비밀번호')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('region', models.CharField(max_length=10, verbose_name='활동지역도')),
                ('city', models.CharField(max_length=10, verbose_name='활동지역시')),
                ('school', models.CharField(max_length=10, null=True, verbose_name='학교')),
                ('matchcount', models.IntegerField(blank=True, default=0, null=True, verbose_name='경기수')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='득점수')),
                ('goalAverage', models.FloatField(blank=True, default=0, null=True, verbose_name='득점률')),
                ('registered_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='등록시간')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='휴대폰 번호')),
                ('auth_number', models.IntegerField(blank=True, null=True, verbose_name='인증 번호')),
            ],
            options={
                'verbose_name': 'FNS 사용자',
                'verbose_name_plural': 'FNS 사용자',
                'db_table': 'FNSUser',
            },
        ),
    ]
