# Generated by Django 2.1.8 on 2019-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191009_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnsuser',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
    ]
