# Generated by Django 2.1.8 on 2019-10-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_fnsuser_isstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnsuser',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='이름'),
        ),
    ]
