# Generated by Django 2.1.8 on 2019-10-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20191018_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnsuser',
            name='name',
            field=models.CharField(max_length=10, verbose_name='이름'),
        ),
    ]
