# Generated by Django 2.1.8 on 2019-11-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_fnsuser_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnsuser',
            name='password',
            field=models.CharField(max_length=150, verbose_name='비밀번호'),
        ),
    ]
