# Generated by Django 2.1.8 on 2020-04-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_fnsuser_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fnsuser',
            name='birthday',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='fnsuser',
            name='informationPolicy',
            field=models.BooleanField(default=True, verbose_name='개인정보처리방침 동의'),
        ),
        migrations.AddField(
            model_name='fnsuser',
            name='servicePolicy',
            field=models.BooleanField(default=True, verbose_name='이용약관 동의'),
        ),
    ]
