# Generated by Django 2.1.8 on 2019-10-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('follow', 'Follow'), ('like', 'Like')], max_length=20),
        ),
    ]
