# Generated by Django 2.1.8 on 2019-10-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20191019_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='PersonalMatching',
            new_name='personalMatching',
        ),
    ]
