# Generated by Django 2.1.8 on 2019-10-19 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
        ('notification', '0005_auto_20191019_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.League'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recruiting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.Recruiting'),
        ),
        migrations.AddField(
            model_name='notification',
            name='teamMatching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.TeamMatching'),
        ),
        migrations.AddField(
            model_name='notification',
            name='userCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('applyTeam', 'ApplyTeam'), ('matchConfirm', 'MatchConfirm'), ('comment', 'Comment')], max_length=20),
        ),
    ]
