# Generated by Django 2.1.8 on 2019-10-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_auto_20191019_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('matchConfirm', 'MatchConfirm'), ('comment', 'Comment'), ('applyTeam', 'ApplyTeam')], max_length=20),
        ),
    ]
