# Generated by Django 2.1.8 on 2019-10-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20191019_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('applyTeam', 'ApplyTeam'), ('comment', 'Comment'), ('matchConfirm', 'MatchConfirm')], max_length=20),
        ),
    ]
