# Generated by Django 2.1.8 on 2019-10-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_auto_20191019_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='comment',
            new_name='text',
        ),
    ]
