# Generated by Django 2.1.8 on 2019-10-20 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('notification', '0011_auto_20191020_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('personalApply', 'personalApply'), ('teamComment', 'teamComment'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingApply', 'recruitingApply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('recruitingComment', 'recruitingComment'), ('teamJoin', 'teamJoin'), ('leagueTeamApply', 'leagueTeamApply'), ('personalComment', 'personalComment'), ('leagueComment', 'leagueComment')], max_length=20),
        ),
    ]
