# Generated by Django 2.1.8 on 2019-10-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20191020_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('recruitingApply', 'recruitingApply'), ('teamComment', 'teamComment'), ('teamJoin', 'teamJoin'), ('recruitingComment', 'recruitingComment'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingAccepted', 'recruitingAccepted'), ('suggestTeamMatching', 'suggestTeamMatching'), ('personalComment', 'personalComment'), ('leagueComment', 'leagueComment'), ('leaguePersonalApply', 'leaguePersonalApply'), ('leagueTeamApply', 'leagueTeamApply'), ('personalApply', 'personalApply')], max_length=20),
        ),
    ]
