# Generated by Django 2.1.8 on 2019-10-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_auto_20191020_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leagueComment', 'leagueComment'), ('teamComment', 'teamComment'), ('leaguePersonalApply', 'leaguePersonalApply'), ('joinTeam', 'joinTeam'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingApply', 'recruitingApply'), ('recruitingComment', 'recruitingComment'), ('personalApply', 'personalApply'), ('personalComment', 'personalComment'), ('recruitingAccepted', 'recruitingAccepted'), ('teamAccepted', 'teamAccepted'), ('leagueTeamApply', 'leagueTeamApply')], max_length=20),
        ),
    ]
