# Generated by Django 2.1.8 on 2019-10-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_auto_20191021_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('personalComment', 'personalComment'), ('recruitingComment', 'recruitingComment'), ('personalApply', 'personalApply'), ('recruitingApply', 'recruitingApply'), ('teamComment', 'teamComment'), ('teamAccepted', 'teamAccepted'), ('leaguePersonalApply', 'leaguePersonalApply'), ('joinTeam', 'joinTeam'), ('leagueComment', 'leagueComment'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingAccepted', 'recruitingAccepted'), ('suggestTeamMatching', 'suggestTeamMatching'), ('leagueTeamApply', 'leagueTeamApply')], max_length=20),
        ),
    ]
