# Generated by Django 2.1.8 on 2019-10-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_personalreply'),
        ('notification', '0015_auto_20191021_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lgComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.LGComment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='personalComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.PersonalComment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='reComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.REComment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tmComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.TMComment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('recruitingApply', 'recruitingApply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamComment', 'teamComment'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingAccepted', 'recruitingAccepted'), ('leaguePersonalApply', 'leaguePersonalApply'), ('leagueTeamApply', 'leagueTeamApply'), ('joinTeam', 'joinTeam'), ('personalComment', 'personalComment'), ('recruitingComment', 'recruitingComment'), ('leagueComment', 'leagueComment'), ('teamReply', 'teamReply'), ('recruitingReply', 'recruitingReply'), ('personalReply', 'personalReply'), ('personalApply', 'personalApply'), ('leagueReply', 'leagueReply'), ('teamAccepted', 'teamAccepted')], max_length=20),
        ),
    ]
