# Generated by Django 2.1.8 on 2019-10-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0018_auto_20191021_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('suggestTeamMatching', 'suggestTeamMatching'), ('teamMatchingApply', 'teamMatchingApply'), ('teamComment', 'teamComment'), ('personalApply', 'personalApply'), ('recruitingAccepted', 'recruitingAccepted'), ('leagueTeamApply', 'leagueTeamApply'), ('recruitingComment', 'recruitingComment'), ('teamReply', 'teamReply'), ('prComment', 'prComment'), ('leagueComment', 'leagueComment'), ('recruitingApply', 'recruitingApply'), ('personalReply', 'personalReply'), ('recruitingReply', 'recruitingReply'), ('leagueReply', 'leagueReply'), ('teamAccepted', 'teamAccepted'), ('leaguePersonalApply', 'leaguePersonalApply'), ('joinTeam', 'joinTeam')], max_length=20),
        ),
    ]
