# Generated by Django 2.1.8 on 2019-11-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0020_auto_20191028_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamAccepted', 'teamAccepted'), ('leagueReply', 'leagueReply'), ('joinTeam', 'joinTeam'), ('leagueComment', 'leagueComment'), ('prComment', 'prComment'), ('teamComment', 'teamComment'), ('leagueTeamApply', 'leagueTeamApply'), ('recruitingReply', 'recruitingReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('recruitingApply', 'recruitingApply'), ('recruitingComment', 'recruitingComment'), ('recruitingAccepted', 'recruitingAccepted'), ('teamReply', 'teamReply'), ('teamMatchingApply', 'teamMatchingApply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('personalReply', 'personalReply'), ('personalApply', 'personalApply')], max_length=20),
        ),
    ]
