# Generated by Django 2.1.8 on 2019-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0021_auto_20191101_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamReply', 'teamReply'), ('joinTeam', 'joinTeam'), ('recruitingApply', 'recruitingApply'), ('personalReply', 'personalReply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('teamAccepted', 'teamAccepted'), ('personalApply', 'personalApply'), ('leagueComment', 'leagueComment'), ('recruitingComment', 'recruitingComment'), ('teamMatchingApply', 'teamMatchingApply'), ('leagueReply', 'leagueReply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('prComment', 'prComment'), ('recruitingAccepted', 'recruitingAccepted'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamComment', 'teamComment'), ('recruitingDenied', 'recruitingDenied'), ('leagueTeamApply', 'leagueTeamApply'), ('recruitingReply', 'recruitingReply')], max_length=30),
        ),
    ]
