# Generated by Django 2.1.8 on 2019-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0022_auto_20191104_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('personalReply', 'personalReply'), ('recruitingReply', 'recruitingReply'), ('recruitingAccepted', 'recruitingAccepted'), ('leagueTeamApply', 'leagueTeamApply'), ('teamReply', 'teamReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamMatchingApply', 'teamMatchingApply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('recruitingDenied', 'recruitingDenied'), ('joinTeam', 'joinTeam'), ('teamAccepted', 'teamAccepted'), ('leaguePersonalApply', 'leaguePersonalApply'), ('prComment', 'prComment'), ('recruitingApply', 'recruitingApply'), ('leagueReply', 'leagueReply'), ('personalApply', 'personalApply'), ('teamComment', 'teamComment'), ('recruitingComment', 'recruitingComment'), ('leagueComment', 'leagueComment')], max_length=30),
        ),
    ]
