# Generated by Django 2.1.8 on 2019-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0023_auto_20191104_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('recruitingDenied', 'recruitingDenied'), ('teamApplicationDenied', 'teamApplicationDenied'), ('prComment', 'prComment'), ('joinTeam', 'joinTeam'), ('personalReply', 'personalReply'), ('teamReply', 'teamReply'), ('recruitingAccepted', 'recruitingAccepted'), ('leaguePersonalApply', 'leaguePersonalApply'), ('recruitingApply', 'recruitingApply'), ('leagueTeamApply', 'leagueTeamApply'), ('personalApply', 'personalApply'), ('teamAccepted', 'teamAccepted'), ('leagueComment', 'leagueComment'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamComment', 'teamComment'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingComment', 'recruitingComment'), ('leagueReply', 'leagueReply'), ('recruitingReply', 'recruitingReply')], max_length=30),
        ),
    ]
