# Generated by Django 2.1.8 on 2019-11-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0025_auto_20191107_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamComment', 'teamComment'), ('leagueComment', 'leagueComment'), ('recruitingAccepted', 'recruitingAccepted'), ('joinTeam', 'joinTeam'), ('suggestTeamMatching', 'suggestTeamMatching'), ('recruitingDenied', 'recruitingDenied'), ('teamReply', 'teamReply'), ('teamAccepted', 'teamAccepted'), ('recruitingComment', 'recruitingComment'), ('recruitingReply', 'recruitingReply'), ('acceptSuggestion', 'acceptSuggestion'), ('teamApplicationDenied', 'teamApplicationDenied'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingApply', 'recruitingApply'), ('prComment', 'prComment'), ('leagueTeamApply', 'leagueTeamApply'), ('personalReply', 'personalReply'), ('personalApply', 'personalApply'), ('leagueReply', 'leagueReply'), ('leaguePersonalApply', 'leaguePersonalApply')], max_length=30),
        ),
    ]
