# Generated by Django 2.1.8 on 2019-11-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0026_auto_20191107_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leagueReply', 'leagueReply'), ('recruitingAccepted', 'recruitingAccepted'), ('joinTeam', 'joinTeam'), ('recruitingComment', 'recruitingComment'), ('prComment', 'prComment'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamAccepted', 'teamAccepted'), ('teamReply', 'teamReply'), ('recruitingDenied', 'recruitingDenied'), ('recruitingApply', 'recruitingApply'), ('leagueComment', 'leagueComment'), ('teamMatchingApply', 'teamMatchingApply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('personalApply', 'personalApply'), ('leagueTeamApply', 'leagueTeamApply'), ('teamComment', 'teamComment'), ('leaguePersonalApply', 'leaguePersonalApply'), ('personalReply', 'personalReply'), ('acceptSuggestion', 'acceptSuggestion'), ('recruitingReply', 'recruitingReply')], max_length=30),
        ),
    ]
