# Generated by Django 2.1.8 on 2019-11-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0027_auto_20191108_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('prComment', 'prComment'), ('recruitingAccepted', 'recruitingAccepted'), ('recruitingApply', 'recruitingApply'), ('personalReply', 'personalReply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('joinTeam', 'joinTeam'), ('teamMatchingApply', 'teamMatchingApply'), ('acceptSuggestion', 'acceptSuggestion'), ('teamComment', 'teamComment'), ('teamAccepted', 'teamAccepted'), ('leagueReply', 'leagueReply'), ('leagueComment', 'leagueComment'), ('leagueTeamApply', 'leagueTeamApply'), ('personalApply', 'personalApply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('leaguePersonalApply', 'leaguePersonalApply'), ('teamReply', 'teamReply'), ('recruitingComment', 'recruitingComment'), ('recruitingDenied', 'recruitingDenied'), ('recruitingReply', 'recruitingReply')], max_length=30),
        ),
    ]
