# Generated by Django 2.1.8 on 2019-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0029_auto_20191110_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamReply', 'teamReply'), ('personalApply', 'personalApply'), ('recruitingReply', 'recruitingReply'), ('acceptSuggestion', 'acceptSuggestion'), ('resultEdit', 'resultEdit'), ('teamAccepted', 'teamAccepted'), ('resultConfirm', 'resultConfirm'), ('prComment', 'prComment'), ('recruitingAccepted', 'recruitingAccepted'), ('joinTeam', 'joinTeam'), ('denySuggestion', 'denySuggestion'), ('resultInput', 'resultInput'), ('leaguePersonalApply', 'leaguePersonalApply'), ('leagueReply', 'leagueReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('leagueComment', 'leagueComment'), ('recruitingDenied', 'recruitingDenied'), ('personalReply', 'personalReply'), ('recruitingComment', 'recruitingComment'), ('teamComment', 'teamComment'), ('recruitingApply', 'recruitingApply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('leagueTeamApply', 'leagueTeamApply'), ('teamMatchingApply', 'teamMatchingApply')], max_length=30),
        ),
    ]
