# Generated by Django 2.1.8 on 2020-03-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0032_auto_20191111_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('suggestTeamMatching', 'suggestTeamMatching'), ('teamApplicationDenied', 'teamApplicationDenied'), ('prComment', 'prComment'), ('teamComment', 'teamComment'), ('recruitingComment', 'recruitingComment'), ('recruitingAccepted', 'recruitingAccepted'), ('recruitingReply', 'recruitingReply'), ('joinTeam', 'joinTeam'), ('denySuggestion', 'denySuggestion'), ('acceptSuggestion', 'acceptSuggestion'), ('leaguePersonalApply', 'leaguePersonalApply'), ('leagueComment', 'leagueComment'), ('recruitingApply', 'recruitingApply'), ('teamAccepted', 'teamAccepted'), ('leagueTeamApply', 'leagueTeamApply'), ('resultConfirm', 'resultConfirm'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingDenied', 'recruitingDenied'), ('personalApply', 'personalApply'), ('teamReply', 'teamReply'), ('resultEdit', 'resultEdit'), ('resultInput', 'resultInput'), ('personalReply', 'personalReply'), ('leagueReply', 'leagueReply')], max_length=30),
        ),
    ]
