# Generated by Django 2.1.8 on 2020-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0033_auto_20200301_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('prComment', 'prComment'), ('personalApply', 'personalApply'), ('teamAccepted', 'teamAccepted'), ('recruitingAccepted', 'recruitingAccepted'), ('leagueReply', 'leagueReply'), ('resultEdit', 'resultEdit'), ('recruitingApply', 'recruitingApply'), ('denySuggestion', 'denySuggestion'), ('resultConfirm', 'resultConfirm'), ('personalReply', 'personalReply'), ('acceptSuggestion', 'acceptSuggestion'), ('teamReply', 'teamReply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('teamComment', 'teamComment'), ('joinTeam', 'joinTeam'), ('leagueComment', 'leagueComment'), ('leaguePersonalApply', 'leaguePersonalApply'), ('resultInput', 'resultInput'), ('recruitingComment', 'recruitingComment'), ('suggestTeamMatching', 'suggestTeamMatching'), ('recruitingDenied', 'recruitingDenied'), ('recruitingReply', 'recruitingReply'), ('teamMatchingApply', 'teamMatchingApply'), ('leagueTeamApply', 'leagueTeamApply')], max_length=30),
        ),
    ]
