# Generated by Django 2.1.8 on 2020-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0034_auto_20200301_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('recruitingAccepted', 'recruitingAccepted'), ('denySuggestion', 'denySuggestion'), ('recruitingComment', 'recruitingComment'), ('leagueTeamApply', 'leagueTeamApply'), ('resultInput', 'resultInput'), ('teamAccepted', 'teamAccepted'), ('teamComment', 'teamComment'), ('personalApply', 'personalApply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('recruitingReply', 'recruitingReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamMatchingApply', 'teamMatchingApply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('joinTeam', 'joinTeam'), ('personalReply', 'personalReply'), ('teamReply', 'teamReply'), ('recruitingDenied', 'recruitingDenied'), ('leagueReply', 'leagueReply'), ('recruitingApply', 'recruitingApply'), ('acceptSuggestion', 'acceptSuggestion'), ('resultEdit', 'resultEdit'), ('resultConfirm', 'resultConfirm'), ('prComment', 'prComment'), ('leagueComment', 'leagueComment')], max_length=30),
        ),
    ]
