# Generated by Django 2.1.8 on 2020-03-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0035_auto_20200303_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('resultInput', 'resultInput'), ('teamApplicationDenied', 'teamApplicationDenied'), ('leagueComment', 'leagueComment'), ('teamComment', 'teamComment'), ('recruitingApply', 'recruitingApply'), ('acceptSuggestion', 'acceptSuggestion'), ('recruitingReply', 'recruitingReply'), ('leagueReply', 'leagueReply'), ('personalReply', 'personalReply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingComment', 'recruitingComment'), ('prComment', 'prComment'), ('teamReply', 'teamReply'), ('leagueTeamApply', 'leagueTeamApply'), ('denySuggestion', 'denySuggestion'), ('resultConfirm', 'resultConfirm'), ('personalApply', 'personalApply'), ('recruitingAccepted', 'recruitingAccepted'), ('resultEdit', 'resultEdit'), ('recruitingDenied', 'recruitingDenied'), ('teamAccepted', 'teamAccepted'), ('joinTeam', 'joinTeam')], max_length=30),
        ),
    ]
