# Generated by Django 2.1.8 on 2020-03-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0036_auto_20200309_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('joinTeam', 'joinTeam'), ('prComment', 'prComment'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingAccepted', 'recruitingAccepted'), ('resultInput', 'resultInput'), ('recruitingDenied', 'recruitingDenied'), ('teamReply', 'teamReply'), ('resultConfirm', 'resultConfirm'), ('teamAccepted', 'teamAccepted'), ('leagueComment', 'leagueComment'), ('teamComment', 'teamComment'), ('personalApply', 'personalApply'), ('acceptSuggestion', 'acceptSuggestion'), ('recruitingApply', 'recruitingApply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('denySuggestion', 'denySuggestion'), ('recruitingReply', 'recruitingReply'), ('leagueTeamApply', 'leagueTeamApply'), ('personalReply', 'personalReply'), ('leagueReply', 'leagueReply'), ('resultEdit', 'resultEdit'), ('recruitingComment', 'recruitingComment'), ('suggestTeamMatching', 'suggestTeamMatching')], max_length=30),
        ),
    ]
