# Generated by Django 2.1.8 on 2020-03-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0037_auto_20200309_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamReply', 'teamReply'), ('leagueComment', 'leagueComment'), ('personalApply', 'personalApply'), ('recruitingApply', 'recruitingApply'), ('personalReply', 'personalReply'), ('recruitingReply', 'recruitingReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('denySuggestion', 'denySuggestion'), ('teamMatchingApply', 'teamMatchingApply'), ('joinTeam', 'joinTeam'), ('recruitingAccepted', 'recruitingAccepted'), ('leaguePersonalApply', 'leaguePersonalApply'), ('teamAccepted', 'teamAccepted'), ('resultInput', 'resultInput'), ('resultConfirm', 'resultConfirm'), ('resultEdit', 'resultEdit'), ('prComment', 'prComment'), ('teamComment', 'teamComment'), ('teamApplicationDenied', 'teamApplicationDenied'), ('recruitingDenied', 'recruitingDenied'), ('leagueTeamApply', 'leagueTeamApply'), ('leagueReply', 'leagueReply'), ('acceptSuggestion', 'acceptSuggestion'), ('recruitingComment', 'recruitingComment')], max_length=30),
        ),
    ]
