# Generated by Django 2.1.8 on 2020-03-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0039_auto_20200309_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('personalApply', 'personalApply'), ('teamReply', 'teamReply'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingApply', 'recruitingApply'), ('acceptSuggestion', 'acceptSuggestion'), ('resultConfirm', 'resultConfirm'), ('leagueTeamApply', 'leagueTeamApply'), ('leagueReply', 'leagueReply'), ('resultInput', 'resultInput'), ('recruitingAccepted', 'recruitingAccepted'), ('prComment', 'prComment'), ('leagueComment', 'leagueComment'), ('leaguePersonalApply', 'leaguePersonalApply'), ('resultEdit', 'resultEdit'), ('teamComment', 'teamComment'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamAccepted', 'teamAccepted'), ('personalReply', 'personalReply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('recruitingComment', 'recruitingComment'), ('recruitingDenied', 'recruitingDenied'), ('denySuggestion', 'denySuggestion'), ('recruitingReply', 'recruitingReply'), ('joinTeam', 'joinTeam')], max_length=30),
        ),
    ]
