# Generated by Django 2.1.8 on 2020-03-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0041_auto_20200320_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamReply', 'teamReply'), ('leagueTeamApply', 'leagueTeamApply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('teamComment', 'teamComment'), ('acceptSuggestion', 'acceptSuggestion'), ('recruitingComment', 'recruitingComment'), ('recruitingDenied', 'recruitingDenied'), ('prComment', 'prComment'), ('recruitingApply', 'recruitingApply'), ('denySuggestion', 'denySuggestion'), ('leagueReply', 'leagueReply'), ('personalReply', 'personalReply'), ('recruitingAccepted', 'recruitingAccepted'), ('resultEdit', 'resultEdit'), ('leaguePersonalApply', 'leaguePersonalApply'), ('resultInput', 'resultInput'), ('resultConfirm', 'resultConfirm'), ('teamAccepted', 'teamAccepted'), ('suggestTeamMatching', 'suggestTeamMatching'), ('joinTeam', 'joinTeam'), ('leagueComment', 'leagueComment'), ('personalApply', 'personalApply'), ('recruitingReply', 'recruitingReply'), ('teamMatchingApply', 'teamMatchingApply')], max_length=30),
        ),
    ]
