# Generated by Django 2.1.8 on 2020-03-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0042_auto_20200320_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('denySuggestion', 'denySuggestion'), ('personalApply', 'personalApply'), ('resultEdit', 'resultEdit'), ('recruitingComment', 'recruitingComment'), ('recruitingReply', 'recruitingReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('acceptSuggestion', 'acceptSuggestion'), ('recruitingApply', 'recruitingApply'), ('teamReply', 'teamReply'), ('resultInput', 'resultInput'), ('joinTeam', 'joinTeam'), ('leagueComment', 'leagueComment'), ('prComment', 'prComment'), ('teamAccepted', 'teamAccepted'), ('personalReply', 'personalReply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('recruitingAccepted', 'recruitingAccepted'), ('leagueTeamApply', 'leagueTeamApply'), ('resultConfirm', 'resultConfirm'), ('leaguePersonalApply', 'leaguePersonalApply'), ('leagueReply', 'leagueReply'), ('recruitingDenied', 'recruitingDenied'), ('teamMatchingApply', 'teamMatchingApply'), ('teamComment', 'teamComment')], max_length=30),
        ),
    ]
