# Generated by Django 2.1.8 on 2020-04-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0045_auto_20200407_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('recruitingAccepted', 'recruitingAccepted'), ('leaguePersonalApply', 'leaguePersonalApply'), ('teamReply', 'teamReply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('teamAccepted', 'teamAccepted'), ('recruitingComment', 'recruitingComment'), ('acceptSuggestion', 'acceptSuggestion'), ('resultConfirm', 'resultConfirm'), ('recruitingApply', 'recruitingApply'), ('joinTeam', 'joinTeam'), ('leagueReply', 'leagueReply'), ('resultInput', 'resultInput'), ('denySuggestion', 'denySuggestion'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamMatchingApply', 'teamMatchingApply'), ('resultEdit', 'resultEdit'), ('teamComment', 'teamComment'), ('recruitingDenied', 'recruitingDenied'), ('leagueComment', 'leagueComment'), ('personalReply', 'personalReply'), ('leagueTeamApply', 'leagueTeamApply'), ('recruitingReply', 'recruitingReply'), ('prComment', 'prComment'), ('personalApply', 'personalApply')], max_length=30),
        ),
    ]
