# Generated by Django 2.1.8 on 2020-04-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0048_auto_20200421_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamComment', 'teamComment'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingComment', 'recruitingComment'), ('recruitingReply', 'recruitingReply'), ('resultEdit', 'resultEdit'), ('suggestTeamMatching', 'suggestTeamMatching'), ('joinTeam', 'joinTeam'), ('leagueReply', 'leagueReply'), ('resultInput', 'resultInput'), ('prComment', 'prComment'), ('resultConfirm', 'resultConfirm'), ('leaguePersonalApply', 'leaguePersonalApply'), ('acceptSuggestion', 'acceptSuggestion'), ('denySuggestion', 'denySuggestion'), ('leagueTeamApply', 'leagueTeamApply'), ('personalReply', 'personalReply'), ('recruitingAccepted', 'recruitingAccepted'), ('teamApplicationDenied', 'teamApplicationDenied'), ('personalAccept', 'personalAccept'), ('personalApply', 'personalApply'), ('personalDeny', 'personalDeny'), ('recruitingApply', 'recruitingApply'), ('teamReply', 'teamReply'), ('teamAccepted', 'teamAccepted'), ('leagueComment', 'leagueComment'), ('recruitingDenied', 'recruitingDenied')], max_length=30),
        ),
    ]
