# Generated by Django 2.1.8 on 2020-04-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0049_auto_20200421_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamAccepted', 'teamAccepted'), ('recruitingDenied', 'recruitingDenied'), ('personalReply', 'personalReply'), ('denySuggestion', 'denySuggestion'), ('resultConfirm', 'resultConfirm'), ('personalApply', 'personalApply'), ('personalAccept', 'personalAccept'), ('personalDeny', 'personalDeny'), ('recruitingReply', 'recruitingReply'), ('prComment', 'prComment'), ('leagueTeamApply', 'leagueTeamApply'), ('recruitingComment', 'recruitingComment'), ('leagueComment', 'leagueComment'), ('resultInput', 'resultInput'), ('leaguePersonalApply', 'leaguePersonalApply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('leagueReply', 'leagueReply'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingAccepted', 'recruitingAccepted'), ('joinTeam', 'joinTeam'), ('recruitingApply', 'recruitingApply'), ('resultEdit', 'resultEdit'), ('teamComment', 'teamComment'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamReply', 'teamReply'), ('acceptSuggestion', 'acceptSuggestion')], max_length=30),
        ),
    ]
