# Generated by Django 2.1.8 on 2020-04-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0051_auto_20200423_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamApplicationDenied', 'teamApplicationDenied'), ('acceptSuggestion', 'acceptSuggestion'), ('leaguePersonalApply', 'leaguePersonalApply'), ('personalReply', 'personalReply'), ('teamAccepted', 'teamAccepted'), ('recruitingComment', 'recruitingComment'), ('personalApply', 'personalApply'), ('personalDeny', 'personalDeny'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingReply', 'recruitingReply'), ('resultEdit', 'resultEdit'), ('joinTeam', 'joinTeam'), ('suggestTeamMatching', 'suggestTeamMatching'), ('personalAccept', 'personalAccept'), ('leagueReply', 'leagueReply'), ('resultConfirm', 'resultConfirm'), ('teamReply', 'teamReply'), ('leagueTeamApply', 'leagueTeamApply'), ('prComment', 'prComment'), ('denySuggestion', 'denySuggestion'), ('resultInput', 'resultInput'), ('recruitingAccepted', 'recruitingAccepted'), ('recruitingDenied', 'recruitingDenied'), ('leagueComment', 'leagueComment'), ('recruitingApply', 'recruitingApply'), ('teamComment', 'teamComment')], max_length=30),
        ),
    ]
