# Generated by Django 2.1.8 on 2020-04-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0052_auto_20200424_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamAccepted', 'teamAccepted'), ('joinTeam', 'joinTeam'), ('teamApplicationDenied', 'teamApplicationDenied'), ('leagueTeamApply', 'leagueTeamApply'), ('recruitingComment', 'recruitingComment'), ('acceptSuggestion', 'acceptSuggestion'), ('personalDeny', 'personalDeny'), ('resultEdit', 'resultEdit'), ('teamComment', 'teamComment'), ('personalReply', 'personalReply'), ('resultInput', 'resultInput'), ('suggestTeamMatching', 'suggestTeamMatching'), ('recruitingReply', 'recruitingReply'), ('personalApply', 'personalApply'), ('personalAccept', 'personalAccept'), ('teamReply', 'teamReply'), ('denySuggestion', 'denySuggestion'), ('resultConfirm', 'resultConfirm'), ('leaguePersonalApply', 'leaguePersonalApply'), ('recruitingDenied', 'recruitingDenied'), ('prComment', 'prComment'), ('leagueComment', 'leagueComment'), ('recruitingApply', 'recruitingApply'), ('leagueReply', 'leagueReply'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingAccepted', 'recruitingAccepted')], max_length=30),
        ),
    ]
