# Generated by Django 2.1.8 on 2020-04-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0053_auto_20200424_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('teamComment', 'teamComment'), ('recruitingDenied', 'recruitingDenied'), ('leagueReply', 'leagueReply'), ('personalAccept', 'personalAccept'), ('personalDeny', 'personalDeny'), ('teamApplicationDenied', 'teamApplicationDenied'), ('leaguePersonalApply', 'leaguePersonalApply'), ('resultInput', 'resultInput'), ('recruitingComment', 'recruitingComment'), ('teamMatchingApply', 'teamMatchingApply'), ('teamReply', 'teamReply'), ('denySuggestion', 'denySuggestion'), ('resultConfirm', 'resultConfirm'), ('recruitingApply', 'recruitingApply'), ('leagueComment', 'leagueComment'), ('personalApply', 'personalApply'), ('prComment', 'prComment'), ('acceptSuggestion', 'acceptSuggestion'), ('resultEdit', 'resultEdit'), ('leagueTeamApply', 'leagueTeamApply'), ('teamAccepted', 'teamAccepted'), ('recruitingReply', 'recruitingReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('joinTeam', 'joinTeam'), ('personalReply', 'personalReply'), ('recruitingAccepted', 'recruitingAccepted')], max_length=30),
        ),
    ]
