# Generated by Django 2.1.8 on 2020-04-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0054_auto_20200425_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('resultEdit', 'resultEdit'), ('recruitingAccepted', 'recruitingAccepted'), ('leagueTeamApply', 'leagueTeamApply'), ('personalApply', 'personalApply'), ('resultInput', 'resultInput'), ('recruitingApply', 'recruitingApply'), ('resultConfirm', 'resultConfirm'), ('prComment', 'prComment'), ('personalReply', 'personalReply'), ('personalAccept', 'personalAccept'), ('recruitingComment', 'recruitingComment'), ('teamAccepted', 'teamAccepted'), ('recruitingReply', 'recruitingReply'), ('teamReply', 'teamReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamComment', 'teamComment'), ('leagueComment', 'leagueComment'), ('personalDeny', 'personalDeny'), ('leaguePersonalApply', 'leaguePersonalApply'), ('acceptSuggestion', 'acceptSuggestion'), ('leagueReply', 'leagueReply'), ('teamApplicationDenied', 'teamApplicationDenied'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingDenied', 'recruitingDenied'), ('denySuggestion', 'denySuggestion'), ('joinTeam', 'joinTeam')], max_length=30),
        ),
    ]
