# Generated by Django 2.1.8 on 2020-04-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0055_auto_20200425_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leagueReply', 'leagueReply'), ('personalAccept', 'personalAccept'), ('acceptSuggestion', 'acceptSuggestion'), ('leagueComment', 'leagueComment'), ('teamComment', 'teamComment'), ('recruitingReply', 'recruitingReply'), ('denySuggestion', 'denySuggestion'), ('teamMatchingApply', 'teamMatchingApply'), ('prComment', 'prComment'), ('personalDeny', 'personalDeny'), ('resultEdit', 'resultEdit'), ('suggestTeamMatching', 'suggestTeamMatching'), ('recruitingComment', 'recruitingComment'), ('teamAccepted', 'teamAccepted'), ('leagueTeamApply', 'leagueTeamApply'), ('joinTeam', 'joinTeam'), ('resultConfirm', 'resultConfirm'), ('recruitingApply', 'recruitingApply'), ('personalApply', 'personalApply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('personalReply', 'personalReply'), ('resultInput', 'resultInput'), ('teamApplicationDenied', 'teamApplicationDenied'), ('recruitingAccepted', 'recruitingAccepted'), ('teamReply', 'teamReply'), ('recruitingDenied', 'recruitingDenied')], max_length=30),
        ),
    ]
