# Generated by Django 2.1.8 on 2020-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0057_auto_20200426_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leagueComment', 'leagueComment'), ('personalDeny', 'personalDeny'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingDenied', 'recruitingDenied'), ('leagueReply', 'leagueReply'), ('resultEdit', 'resultEdit'), ('resultConfirm', 'resultConfirm'), ('recruitingComment', 'recruitingComment'), ('leagueTeamApply', 'leagueTeamApply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('personalReply', 'personalReply'), ('resultInput', 'resultInput'), ('personalAccept', 'personalAccept'), ('prComment', 'prComment'), ('teamComment', 'teamComment'), ('teamReply', 'teamReply'), ('recruitingAccepted', 'recruitingAccepted'), ('personalApply', 'personalApply'), ('denySuggestion', 'denySuggestion'), ('teamAccepted', 'teamAccepted'), ('teamApplicationDenied', 'teamApplicationDenied'), ('recruitingApply', 'recruitingApply'), ('recruitingReply', 'recruitingReply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('joinTeam', 'joinTeam'), ('acceptSuggestion', 'acceptSuggestion')], max_length=30),
        ),
    ]
