# Generated by Django 2.1.8 on 2020-04-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0058_auto_20200426_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('prComment', 'prComment'), ('leaguePersonalApply', 'leaguePersonalApply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('leagueComment', 'leagueComment'), ('teamReply', 'teamReply'), ('leagueReply', 'leagueReply'), ('recruitingApply', 'recruitingApply'), ('resultInput', 'resultInput'), ('recruitingAccepted', 'recruitingAccepted'), ('resultEdit', 'resultEdit'), ('leagueTeamApply', 'leagueTeamApply'), ('teamMatchingApply', 'teamMatchingApply'), ('recruitingComment', 'recruitingComment'), ('recruitingDenied', 'recruitingDenied'), ('teamApplicationDenied', 'teamApplicationDenied'), ('joinTeam', 'joinTeam'), ('acceptSuggestion', 'acceptSuggestion'), ('personalAccept', 'personalAccept'), ('denySuggestion', 'denySuggestion'), ('teamAccepted', 'teamAccepted'), ('recruitingReply', 'recruitingReply'), ('personalDeny', 'personalDeny'), ('resultConfirm', 'resultConfirm'), ('teamComment', 'teamComment'), ('personalReply', 'personalReply'), ('personalApply', 'personalApply')], max_length=30),
        ),
    ]
