# Generated by Django 2.1.8 on 2020-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0060_auto_20200427_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('personalReply', 'personalReply'), ('teamReply', 'teamReply'), ('teamComment', 'teamComment'), ('leagueComment', 'leagueComment'), ('teamApplicationDenied', 'teamApplicationDenied'), ('leaguePersonalApply', 'leaguePersonalApply'), ('recruitingReply', 'recruitingReply'), ('resultInput', 'resultInput'), ('recruitingComment', 'recruitingComment'), ('recruitingAccepted', 'recruitingAccepted'), ('resultEdit', 'resultEdit'), ('resultConfirm', 'resultConfirm'), ('joinTeam', 'joinTeam'), ('teamAccepted', 'teamAccepted'), ('personalAccept', 'personalAccept'), ('recruitingDenied', 'recruitingDenied'), ('acceptSuggestion', 'acceptSuggestion'), ('denySuggestion', 'denySuggestion'), ('leagueTeamApply', 'leagueTeamApply'), ('personalDeny', 'personalDeny'), ('teamMatchingApply', 'teamMatchingApply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('prComment', 'prComment'), ('leagueReply', 'leagueReply'), ('recruitingApply', 'recruitingApply'), ('personalApply', 'personalApply')], max_length=30),
        ),
    ]
