# Generated by Django 2.1.8 on 2020-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0062_auto_20200428_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('joinTeam', 'joinTeam'), ('leaguePersonalApply', 'leaguePersonalApply'), ('teamAccepted', 'teamAccepted'), ('personalDeny', 'personalDeny'), ('recruitingApply', 'recruitingApply'), ('personalReply', 'personalReply'), ('resultConfirm', 'resultConfirm'), ('prComment', 'prComment'), ('recruitingDenied', 'recruitingDenied'), ('acceptSuggestion', 'acceptSuggestion'), ('teamMatchingApply', 'teamMatchingApply'), ('resultEdit', 'resultEdit'), ('leagueReply', 'leagueReply'), ('denySuggestion', 'denySuggestion'), ('leagueTeamApply', 'leagueTeamApply'), ('suggestTeamMatching', 'suggestTeamMatching'), ('teamReply', 'teamReply'), ('recruitingReply', 'recruitingReply'), ('leagueComment', 'leagueComment'), ('resultInput', 'resultInput'), ('teamApplicationDenied', 'teamApplicationDenied'), ('personalApply', 'personalApply'), ('personalAccept', 'personalAccept'), ('recruitingAccepted', 'recruitingAccepted'), ('teamComment', 'teamComment'), ('recruitingComment', 'recruitingComment')], max_length=30),
        ),
    ]
