# Generated by Django 2.1.8 on 2020-04-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0063_auto_20200428_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('personalApply', 'personalApply'), ('leagueTeamApply', 'leagueTeamApply'), ('recruitingComment', 'recruitingComment'), ('recruitingDenied', 'recruitingDenied'), ('recruitingApply', 'recruitingApply'), ('leagueReply', 'leagueReply'), ('recruitingAccepted', 'recruitingAccepted'), ('teamApplicationDenied', 'teamApplicationDenied'), ('leagueComment', 'leagueComment'), ('prComment', 'prComment'), ('teamReply', 'teamReply'), ('personalReply', 'personalReply'), ('leaguePersonalApply', 'leaguePersonalApply'), ('personalAccept', 'personalAccept'), ('resultConfirm', 'resultConfirm'), ('resultInput', 'resultInput'), ('teamComment', 'teamComment'), ('teamAccepted', 'teamAccepted'), ('denySuggestion', 'denySuggestion'), ('joinTeam', 'joinTeam'), ('acceptSuggestion', 'acceptSuggestion'), ('resultEdit', 'resultEdit'), ('suggestTeamMatching', 'suggestTeamMatching'), ('recruitingReply', 'recruitingReply'), ('teamMatchingApply', 'teamMatchingApply'), ('personalDeny', 'personalDeny')], max_length=30),
        ),
    ]
