# Generated by Django 2.1.8 on 2019-10-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=10)),
                ('introduction', models.TextField(max_length=300)),
                ('win', models.IntegerField(blank=True, default=0, null=True)),
                ('draw', models.IntegerField(blank=True, default=0, null=True)),
                ('lose', models.IntegerField(blank=True, default=0, null=True)),
                ('matchcount', models.IntegerField(blank=True, default=0, null=True)),
                ('point', models.IntegerField(blank=True, default=0, null=True)),
                ('gf', models.IntegerField(blank=True, default=0, null=True)),
                ('ga', models.IntegerField(blank=True, default=0, null=True)),
                ('gd', models.IntegerField(blank=True, default=0, null=True)),
                ('rank', models.CharField(default=0, max_length=30, null=True)),
                ('teamimg', models.ImageField(null=True, upload_to='teamimg')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('applied_member', models.ManyToManyField(blank=True, default=0, related_name='applied', to='account.FNSUser')),
                ('teamleader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain', to='account.FNSUser')),
            ],
        ),
    ]
