# Generated by Django 2.1.8 on 2019-11-07 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='등록시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cs',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
    ]
