# Generated by Django 2.1.8 on 2019-10-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecidedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeFrom', models.DateTimeField()),
                ('timeTo', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('my_suggest', models.BooleanField(default=False)),
                ('vs_suggest', models.BooleanField(default=False)),
                ('my_confirm', models.BooleanField(default=False)),
                ('vs_confirm', models.BooleanField(default=False)),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.TeamMatching')),
                ('myTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myDecidedTeam', to='team.Team')),
                ('vsTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vsDecidedTeam', to='team.Team')),
            ],
        ),
    ]
