# Generated by Django 2.1.8 on 2019-11-11 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decidedMatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decidedmatch',
            name='match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decidedMatch', to='match.TeamMatching'),
        ),
    ]
