# Generated by Django 2.1.8 on 2019-10-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_fnsuser_teamname'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.FNSUser')),
            ],
        ),
        migrations.CreateModel(
            name='LGComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='match.League')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FNSUser')),
            ],
        ),
        migrations.CreateModel(
            name='LgPlayerAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.League')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FNSUser')),
            ],
        ),
        migrations.CreateModel(
            name='LgTeamAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('time_from', models.DateTimeField(blank=True, null=True)),
                ('time_to', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('rank', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('attendance', models.ManyToManyField(blank=True, default=0, related_name='attendance', to='account.FNSUser')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.FNSUser')),
            ],
        ),
        migrations.CreateModel(
            name='REComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('rank', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('accepted_player', models.ManyToManyField(blank=True, related_name='accepted_player', to='account.FNSUser')),
                ('applied_player', models.ManyToManyField(blank=True, related_name='applied_player', to='account.FNSUser')),
                ('myteam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitMyTeam', to='team.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.FNSUser')),
                ('vs_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitVs_Team', to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('time_from', models.DateTimeField()),
                ('time_to', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('myteam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myteam', to='team.Team')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.FNSUser')),
                ('vs_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vs_team', to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TmAppliedTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='match.TeamMatching')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TMComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='match.TeamMatching')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FNSUser')),
            ],
        ),
        migrations.AddField(
            model_name='recomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='match.Recruiting'),
        ),
        migrations.AddField(
            model_name='recomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FNSUser'),
        ),
        migrations.AddField(
            model_name='personalcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='match.PersonalMatching'),
        ),
        migrations.AddField(
            model_name='personalcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.FNSUser'),
        ),
    ]
