# Generated by Django 2.1.8 on 2019-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_leaguereply_recruitingreply_teamreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatching',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
