# Generated by Django 2.1.8 on 2019-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_teammatching_is_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatching',
            name='rank',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
