# Generated by Django 2.1.8 on 2020-03-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20191104_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmatching',
            name='sport',
            field=models.CharField(default='Futsal', max_length=15),
        ),
        migrations.AddField(
            model_name='recruiting',
            name='sport',
            field=models.CharField(default='Futsal', max_length=15),
        ),
        migrations.AddField(
            model_name='teammatching',
            name='sport',
            field=models.CharField(default='Futsal', max_length=15),
        ),
    ]
