# Generated by Django 2.1.8 on 2020-04-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_auto_20200423_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalmatching',
            old_name='number',
            new_name='totalNumber',
        ),
        migrations.AddField(
            model_name='personalmatching',
            name='recruitNumber',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
