# Generated by Django 2.1.8 on 2020-04-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_auto_20200424_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalmatching',
            old_name='totalNumber',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='personalmatching',
            name='recruitNumber',
        ),
    ]
