# Generated by Django 2.1.8 on 2020-04-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_auto_20200425_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalmatching',
            name='location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
