# Generated by Django 2.1.8 on 2020-04-27 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('match', '0015_auto_20200426_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammatching',
            name='myteam',
        ),
        migrations.RemoveField(
            model_name='teammatching',
            name='title',
        ),
        migrations.RemoveField(
            model_name='teammatching',
            name='vs_team',
        ),
        migrations.AddField(
            model_name='teammatching',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='지역 시/군/구'),
        ),
        migrations.AddField(
            model_name='teammatching',
            name='joinFee',
            field=models.IntegerField(blank=True, null=True, verbose_name='참가비'),
        ),
        migrations.AddField(
            model_name='teammatching',
            name='myTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myTeam', to='team.Team'),
        ),
        migrations.AddField(
            model_name='teammatching',
            name='region',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='지역 시/도'),
        ),
        migrations.AddField(
            model_name='teammatching',
            name='vsTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsTeam', to='team.Team'),
        ),
        migrations.AlterField(
            model_name='teammatching',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamMatching', to='reservation.PlaygroundList'),
        ),
        migrations.AlterField(
            model_name='tmappliedteam',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliedTeam', to='match.TeamMatching'),
        ),
    ]
