# Generated by Django 2.1.8 on 2020-04-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_auto_20200427_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatching',
            name='isReserved',
            field=models.CharField(default='매칭 후 대관', max_length=10, null=True, verbose_name='구장대관현황'),
        ),
    ]
