# Generated by Django 2.1.8 on 2020-04-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0017_teammatching_isreserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammatching',
            old_name='is_applied',
            new_name='isApplied',
        ),
    ]
