# Generated by Django 2.1.8 on 2020-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playgroundlist',
            name='playgorundPhoto',
            field=models.ImageField(null=True, upload_to='playground'),
        ),
    ]
