# Generated by Django 2.1.8 on 2020-03-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200304_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playgroundlist',
            name='playgorundPhoto',
        ),
    ]
