# Generated by Django 2.1.8 on 2020-03-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_playgroundlist_playgorundphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playgroundlist',
            old_name='playgroundLoation',
            new_name='playgroundLocation',
        ),
    ]
