# Generated by Django 2.1.8 on 2020-03-04 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20200304_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroundlist',
            name='weekDayPrice',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playgroundlist',
            name='weekNightPrice',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playgroundlist',
            name='weekendDayPrice',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playgroundlist',
            name='weekendNightPrice',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playgroundlist',
            name='playgroundInfo',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='playgroundlist',
            name='playgroundOption1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playgroundlist',
            name='playgroundOption2',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playgroundlist',
            name='playgroundOption3',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playgroundlist',
            name='playgroundOption4',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playgroundlist',
            name='playgroundOption5',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playgroundlist',
            name='playgroundOption6',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playgroundlist',
            name='possibleReservation',
            field=models.BooleanField(default=True),
        ),
    ]
