# Generated by Django 2.1.8 on 2020-03-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_playgroundlist_playgorundphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playgroundName', models.CharField(max_length=100)),
                ('reservationDate', models.CharField(max_length=10)),
                ('reservationTime', models.CharField(max_length=10)),
                ('resercationUserId', models.CharField(max_length=45)),
                ('reservationUserName', models.CharField(max_length=10)),
                ('resercationUserPhone', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
