# Generated by Django 2.1.8 on 2020-03-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_reservationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlist',
            name='playgroundName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.PlaygroundList'),
        ),
    ]
