# Generated by Django 2.1.8 on 2020-04-21 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_reservationlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservedGround', to='account.FNSUser'),
        ),
    ]
