# Generated by Django 2.1.8 on 2020-04-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20200421_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='playgroundlist',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='소재지(시/군/구)'),
        ),
        migrations.AddField(
            model_name='playgroundlist',
            name='region',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='소재지(시/도)'),
        ),
    ]
