# Generated by Django 2.1.8 on 2020-04-27 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_auto_20200422_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationlist',
            name='playgroundName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reservation.PlaygroundList'),
        ),
    ]
